name: Compile

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Build with Maven
        run: mvn -B package
      - name: Copy file to home directory
        run: mv target/floodgate* ./floodgate-skript.jar
      - name: Archive artifacts (Spigot)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Floodgate-Skript
          path: ./floodgate-skript.jar
      - name: Push
        uses: github-actions-x/commit@v2.6
        if: success()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'Publish JAR file'
          force-add: 'true'
          files: ./floodgate-skript.jar
          name: GHActions
